version: '3.8'
services:
  api:
    build:
      context: /home/vasil/final-project/api
      dockerfile: Dockerfile
    container_name: api_container
    ports:
      - "5000:5000"
    depends_on:
      - db
    #env_file:
    #  - /home/vasil/final-project/api/.env
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: bookstore_db

  web_client:
    build:
      context: /home/vasil/final-project/web_client
      dockerfile: Dockerfile
    container_name: web_client_container
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      REACT_APP_SERVER_URL: "http://192.168.100.47:5000"

  db:
    image: postgres:13
    container_name: databasa_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bookstore_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: vasil@vasil.al
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

volumes:
  pgdata:
