version: '3.8'
services:
  api:
    build: .
    container_name: api_container
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/bookstore_db

  db:
    image: postgres:13
    container_name: databasa_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bookstore_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

  volumes:
    pgdata:
