version: '3.8'
services:
  api:
    build: .
    container_name: api_container_g1
    ports:
      - "5000:5000"
    depends_on:
      - databasa
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}

  databasa:
    image: postgres:latest
    container_name: databasa
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - databasag1:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container_g1
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: skuadra@skuadra.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  databasag1:
